replicaCount: 2

image:
  repository: ghcr.io/security-org-230982/simple-game
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001

podSecurityContext:
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

networkPolicy:
  enabled: true