{{- if .Values.rbacRisky.enabled }}

# 1. Wildcard admin cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
# 2. Secrets Reader + Pod Exec role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: game-secrets-exec
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["create"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "patch"]

---
# 3. Default ServiceAccount Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-default-sa-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: game-secrets-exec

---
# 4. RBAC Escalation ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-rbac-escalation
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
    verbs: ["create", "update", "patch", "bind", "escalate"]

---
# 5. RBAC Escalation Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-rbac-escalation-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: game-rbac-escalation

---
# 6. Admission Webhook Tampering ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-webhook-admin
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["create", "update", "patch", "delete"]

---
# 7. Admission Webhook Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-webhook-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: game-webhook-admin

{{- end }}