apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::608311475263:role/default-eks-node-group-20260315204227176500000002
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::608311475263:user/vikram
      username: trivikram
      groups:
      - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system