name: terraform-plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'helm/**'
      - '.github/workflows/terraform-plan.yaml'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secrets-scan:
    uses: security-org-230982/security-engineering/.github/workflows/gitleaks.yaml@main
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  iac-scan:
    uses: security-org-230982/security-engineering/.github/workflows/iac-static-scans.yaml@main

  deploy-gates:
    uses: security-org-230982/security-engineering/.github/workflows/platform-deploy-gates.yaml@main
    with:
      image-ref: ghcr.io/security-org-230982/simple-game:main
      chart-path: helm/simple-game
      values-file: helm/simple-game/values.yaml
      certificate-identity: "https://github.com/security-org-230982/product-engineering/.github/workflows/build-test-publish.yaml@refs/heads/main"

  helm-chart-scan:
    uses: security-org-230982/security-engineering/.github/workflows/helm-chart-scan.yaml@main

  terraform-plan:
    runs-on: ubuntu-latest
    needs: 
      - secrets-scan
      - iac-scan
      - deploy-gates
      - helm-chart-scan
    defaults:
      run:
        working-directory: terraform/environments/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - run: terraform init
      - run: terraform fmt -check -recursive ../..
      - run: terraform validate
      - run: terraform plan -input=false -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/environments/dev/tfplan